#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const LEVELS_DIR = path.join(__dirname, "..", "levels");

function clone(value) {
  return JSON.parse(JSON.stringify(value));
}

function deepMerge(base, override) {
  if (!override || typeof override !== "object" || Array.isArray(override)) return clone(override);
  const out = clone(base);
  Object.keys(override).forEach((key) => {
    const ov = override[key];
    const bv = out[key];
    if (ov && typeof ov === "object" && !Array.isArray(ov) && bv && typeof bv === "object" && !Array.isArray(bv)) {
      out[key] = deepMerge(bv, ov);
    } else {
      out[key] = clone(ov);
    }
  });
  return out;
}

const archetypes = {
  scout: {
    sprite: "enemyBlue2",
    hull: 20,
    shield: 0,
    armor: 0,
    speed: 90,
    score: 90,
    baseCredit: 12,
    radius: 16,
    pattern: "zigzag",
    patternParams: { amplitude: 95, frequency: 3.2 },
  },
  fighter: {
    sprite: "enemyRed3",
    hull: 30,
    shield: 0,
    armor: 0,
    speed: 80,
    score: 130,
    baseCredit: 16,
    radius: 20,
    pattern: "swoop",
    patternParams: { amplitude: 70, frequency: 2.9 },
  },
  drone: {
    sprite: "enemyBlue3",
    hull: 24,
    shield: 18,
    armor: 0,
    speed: 74,
    score: 120,
    baseCredit: 14,
    radius: 16,
    pattern: "zigzag",
    patternParams: { amplitude: 75, frequency: 2.8 },
    shieldRegen: 8,
  },
  gnat: {
    sprite: "enemyRed2",
    hull: 12,
    shield: 0,
    armor: 0,
    speed: 162,
    score: 72,
    baseCredit: 10,
    radius: 12,
    pattern: "zigzag",
    patternParams: { amplitude: 205, frequency: 6.0 },
  },
  dart: {
    sprite: "enemyBlue2",
    hull: 17,
    shield: 0,
    armor: 0,
    speed: 148,
    score: 108,
    baseCredit: 12,
    radius: 16,
    pattern: "swoop",
    patternParams: { amplitude: 120, frequency: 5.2 },
  },
  spark: {
    sprite: "enemyGreen4",
    hull: 15,
    shield: 28,
    armor: 0,
    speed: 140,
    score: 160,
    baseCredit: 18,
    radius: 18,
    pattern: "strafe",
    fireRate: 1.6,
    fireMode: "spread",
    fireCount: 5,
    fireSpread: 0.9,
    shieldRegen: 14,
  },
  plated: {
    sprite: "enemyBlack4",
    hull: 26,
    shield: 0,
    armor: 64,
    armorClass: 9,
    speed: 44,
    score: 190,
    baseCredit: 22,
    radius: 22,
    pattern: "drift",
    fireRate: 2.8,
  },
  shieldkite: {
    sprite: "enemyGreen5",
    hull: 22,
    shield: 70,
    armor: 0,
    speed: 64,
    score: 150,
    baseCredit: 16,
    radius: 18,
    pattern: "strafe",
    fireMode: "spread",
    fireCount: 5,
    fireSpread: 0.8,
    fireRate: 2.4,
    shieldRegen: 14,
  },
  skitter: {
    sprite: "enemyBlue5",
    hull: 24,
    shield: 0,
    armor: 0,
    speed: 122,
    score: 150,
    baseCredit: 18,
    radius: 18,
    ai: "skitter",
    aiParams: { dodgeRadius: 160, dodgeStrength: 1.75 },
    fireRate: 2.0,
    fireMode: "spread",
    fireCount: 3,
    fireSpread: 0.56,
    bulletSpeed: 190,
  },
  sentinel: {
    sprite: "enemyBlack3",
    hull: 34,
    shield: 34,
    armor: 0,
    speed: 82,
    score: 190,
    baseCredit: 24,
    radius: 22,
    ai: "sentinel",
    aiParams: { holdY: 150, slideSpeed: 0.88, keepOut: 140 },
    fireRate: 1.55,
    fireMode: "aim",
    bulletSpeed: 210,
  },
  duelist: {
    sprite: "enemyRed5",
    hull: 32,
    shield: 0,
    armor: 72,
    armorClass: 8,
    speed: 95,
    score: 230,
    baseCredit: 28,
    radius: 20,
    ai: "duelist",
    aiParams: { holdY: 190, standoff: 240, strafeSpeed: 1.08 },
    fireRate: 1.65,
    fireMode: "aim",
    bulletSpeed: 215,
  },
  stalker: {
    sprite: "enemyBlue5",
    hull: 34,
    shield: 22,
    armor: 0,
    speed: 112,
    score: 290,
    baseCredit: 34,
    radius: 18,
    ai: "stalker",
    aggroRadius: 240,
    fireRate: 1.8,
    fireMode: "aim",
    shieldRegen: 10,
  },
  escort: {
    sprite: "enemyBlack3",
    hull: 34,
    shield: 0,
    armor: 96,
    armorClass: 10,
    speed: 62,
    score: 250,
    baseCredit: 30,
    radius: 20,
    pattern: "strafe",
    fireMode: "spread",
    fireCount: 5,
    fireSpread: 0.9,
    fireRate: 1.9,
  },
  tank: {
    sprite: "ufoYellow",
    hull: 48,
    shield: 0,
    armor: 150,
    armorClass: 12,
    speed: 30,
    score: 340,
    baseCredit: 42,
    radius: 30,
    ai: "transport",
    fireMode: "aim",
    fireRate: 3.0,
    bulletSpeed: 160,
  },
  bulwark: {
    sprite: "ufoBlue",
    hull: 62,
    shield: 0,
    armor: 250,
    armorClass: 14,
    speed: 24,
    score: 420,
    baseCredit: 52,
    radius: 34,
    ai: "transport",
    fireRate: 3.2,
  },
  hunter: {
    sprite: "enemyGreen4",
    hull: 38,
    shield: 0,
    armor: 18,
    armorClass: 4,
    speed: 120,
    score: 250,
    baseCredit: 32,
    radius: 20,
    ai: "hunter",
    fireRate: 2.1,
  },
};

const bossByLevel = {
  level1: {
    sprite: "assets/generated/boss_manta.png",
    hull: 310,
    shield: 110,
    armor: 0,
    armorClass: 0,
    shieldRegen: 8,
    speed: 74,
    score: 900,
    baseCredit: 180,
    radius: 44,
    pattern: "bossSweep",
    isBoss: true,
    fireRate: 1.3,
    fireMode: "radial",
    fireCount: 12,
    bulletSpeed: 165,
    spriteScale: 0.71,
  },
  level2: {
    sprite: "assets/generated/boss_trident.png",
    hull: 400,
    shield: 0,
    armor: 190,
    armorClass: 10,
    speed: 82,
    score: 1200,
    baseCredit: 250,
    radius: 48,
    pattern: "bossSweep",
    isBoss: true,
    fireRate: 1.15,
    fireMode: "radial",
    fireCount: 15,
    bulletSpeed: 175,
    spriteScale: 0.95,
  },
  level3: {
    sprite: "assets/generated/boss_warden3.png",
    hull: 450,
    shield: 240,
    armor: 100,
    armorClass: 8,
    shieldRegen: 10,
    speed: 90,
    score: 1600,
    baseCredit: 320,
    radius: 54,
    pattern: "bossSweep",
    isBoss: true,
    fireRate: 1.0,
    fireMode: "radial",
    fireCount: 18,
    bulletSpeed: 184,
    spriteScale: 0.86,
  },
  level4: {
    sprite: "assets/generated/boss_serpent.png",
    hull: 560,
    shield: 320,
    armor: 280,
    armorClass: 11,
    shieldRegen: 11,
    speed: 96,
    score: 2200,
    baseCredit: 460,
    radius: 60,
    pattern: "bossAdvanceSweep",
    patternParams: {
      pause: 0.85,
      advance: 58,
      advanceTime: 0.7,
      sweepDuration: 2.4,
      retreatTime: 0.8,
      depth: 76,
    },
    isBoss: true,
    fireRate: 0.9,
    fireMode: "radial",
    fireCount: 21,
    bulletSpeed: 192,
    spriteScale: 0.75,
  },
  level5: {
    sprite: "assets/generated/boss_warden5.png",
    hull: 700,
    shield: 420,
    armor: 460,
    armorClass: 12,
    shieldRegen: 12,
    speed: 108,
    score: 3000,
    baseCredit: 700,
    radius: 66,
    pattern: "bossAdvanceSweep",
    patternParams: {
      pause: 0.78,
      advance: 66,
      advanceTime: 0.64,
      sweepDuration: 2.25,
      retreatTime: 0.78,
      depth: 82,
    },
    isBoss: true,
    fireRate: 0.76,
    fireMode: "radial",
    fireCount: 24,
    bulletSpeed: 205,
    spriteScale: 1.03,
  },
  level6: {
    sprite: "assets/generated/boss_halo.png",
    hull: 920,
    shield: 560,
    armor: 640,
    armorClass: 13,
    shieldRegen: 14,
    speed: 114,
    score: 3800,
    baseCredit: 850,
    radius: 68,
    pattern: "bossAdvanceSweep",
    patternParams: {
      pause: 0.74,
      advance: 72,
      advanceTime: 0.62,
      sweepDuration: 2.1,
      retreatTime: 0.72,
      depth: 90,
    },
    isBoss: true,
    empImmune: true,
    fireRate: 0.66,
    fireMode: "radial",
    fireCount: 27,
    bulletSpeed: 214,
    spriteScale: 0.72,
  },
  level7: {
    sprite: "assets/generated/boss_fortress.png",
    hull: 1280,
    shield: 760,
    armor: 900,
    armorClass: 14,
    shieldRegen: 16,
    speed: 118,
    score: 4600,
    baseCredit: 1080,
    radius: 76,
    pattern: "bossOrbit",
    patternParams: {
      warmupTime: 0.6,
      radiusX: 320,
      radiusY: 95,
      orbitSpeed: 0.78,
      wobble: 22,
    },
    isBoss: true,
    empImmune: true,
    fireRate: 0.56,
    fireMode: "radial",
    fireCount: 30,
    bulletSpeed: 224,
    spriteScale: 0.96,
  },
  level8: {
    sprite: "assets/generated/boss_anvil.png",
    hull: 1680,
    shield: 1040,
    armor: 1240,
    armorClass: 16,
    shieldRegen: 20,
    speed: 124,
    score: 6200,
    baseCredit: 1450,
    radius: 82,
    pattern: "bossOrbit",
    patternParams: {
      warmupTime: 0.55,
      radiusX: 340,
      radiusY: 108,
      orbitSpeed: 0.86,
      wobble: 26,
    },
    isBoss: true,
    empImmune: true,
    fireRate: 0.46,
    fireMode: "radial",
    fireCount: 34,
    bulletSpeed: 236,
    spriteScale: 0.92,
  },
};

function enemy(type, overrides = {}) {
  return deepMerge(archetypes[type], overrides);
}

function boss(levelId, overrides = {}) {
  return deepMerge(bossByLevel[levelId], overrides);
}

const levels = {
  level1: {
    id: "level1",
    name: "First Contact",
    background: "blue",
    music: "01_lift_off_b.ogg",
    difficulty: "Easy",
    description: "Basic pirate patrols with one shielded drone wing. Learn target priority.",
    completeOnBoss: true,
    enemyTypes: {
      scout: enemy("scout", { hull: 18, speed: 86, score: 88 }),
      fighter: enemy("fighter", { hull: 28, speed: 74, score: 124 }),
      drone: enemy("drone", { hull: 22, shield: 16, shieldRegen: 7, speed: 72 }),
      lurker: enemy("stalker", { hull: 24, shield: 0, speed: 70, fireRate: 2.3, baseCredit: 20 }),
      boss: boss("level1"),
    },
    events: [
      { time: 1, type: "scout", count: 6, interval: 0.45 },
      { time: 6, type: "fighter", count: 4, interval: 0.8 },
      { time: 10, type: "drone", count: 2, interval: 1.1 },
      { time: 13, type: "scout", count: 8, interval: 0.35 },
      { time: 18, type: "lurker", count: 2, interval: 1.3 },
      { time: 24, type: "fighter", count: 6, interval: 0.65 },
      { time: 32, type: "drone", count: 3, interval: 1.0 },
      { time: 42, type: "boss", count: 1 },
    ],
  },

  level1_swarm: {
    id: "level1_swarm",
    baseLevel: "level1",
    variant: "swarm",
    name: "First Contact: Swarm",
    background: "blue",
    music: "01_lift_off_b.ogg",
    difficulty: "Easy",
    description: "Fast interceptor cloud with light shields. Clear lanes before they stack.",
    enemyScale: { hp: 0.92, damage: 0.95 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 11, speed: 156 }),
      dart: enemy("dart", { hull: 15, speed: 144 }),
      spark: enemy("spark", { hull: 12, shield: 20, speed: 132, fireRate: 1.9 }),
      drone: enemy("drone", { hull: 20, shield: 14, speed: 74, shieldRegen: 7 }),
      boss: boss("level1"),
    },
    events: [
      { time: 1, type: "gnat", count: 12, interval: 0.25 },
      { time: 6, type: "dart", count: 8, interval: 0.45 },
      { time: 10, type: "spark", count: 2, interval: 1.1 },
      { time: 14, type: "gnat", count: 16, interval: 0.2 },
      { time: 20, type: "dart", count: 10, interval: 0.35 },
      { time: 28, type: "drone", count: 4, interval: 0.9 },
      { time: 34, type: "gnat", count: 14, interval: 0.22 },
      { time: 42, type: "boss", count: 1 },
    ],
  },

  level1_armored: {
    id: "level1_armored",
    baseLevel: "level1",
    variant: "armored",
    name: "First Contact: Armored",
    background: "blue",
    music: "01_lift_off_b.ogg",
    difficulty: "Easy+",
    description: "Few targets, thick plating. Focus fire and avoid chip-damage builds.",
    enemyScale: { hp: 1.12, damage: 1.04 },
    completeOnBoss: true,
    enemyTypes: {
      drone: enemy("drone", { hull: 24, shield: 18, shieldRegen: 8 }),
      plated: enemy("plated", { hull: 20, armor: 46, armorClass: 7, speed: 40 }),
      escort: enemy("escort", { hull: 28, armor: 70, armorClass: 8, speed: 54, fireRate: 2.1 }),
      tank: enemy("tank", { hull: 34, armor: 90, armorClass: 9, speed: 26, fireRate: 3.3 }),
      boss: boss("level1", { hull: 330, shield: 80, armor: 60, armorClass: 6 }),
    },
    events: [
      { time: 2, type: "drone", count: 4, interval: 0.9 },
      { time: 8, type: "plated", count: 3, interval: 1.2 },
      { time: 15, type: "escort", count: 2, interval: 1.3 },
      { time: 24, type: "drone", count: 5, interval: 0.8 },
      { time: 31, type: "tank", count: 1 },
      { time: 36, type: "escort", count: 3, interval: 1.2 },
      { time: 42, type: "boss", count: 1 },
    ],
  },

  level2: {
    id: "level2",
    name: "Orion Drift",
    background: "purple",
    music: "02_stillness_of_space.ogg",
    difficulty: "Medium",
    description: "Armor appears in force. Sentinel lines pin your movement while plated hulls soak shots.",
    completeOnBoss: true,
    enemyTypes: {
      scout: enemy("scout", { hull: 22, speed: 96, score: 108, baseCredit: 14 }),
      fighter: enemy("fighter", { hull: 34, speed: 86, score: 150, baseCredit: 20 }),
      sentinel: enemy("sentinel", { hull: 28, shield: 24, speed: 80, fireRate: 1.75 }),
      plated: enemy("plated", { hull: 24, armor: 58, armorClass: 8, speed: 42, fireRate: 2.6 }),
      hunter: enemy("hunter", { hull: 34, armor: 20, armorClass: 4, speed: 102, fireRate: 2.0 }),
      boss: boss("level2"),
    },
    events: [
      { time: 1, type: "scout", count: 8, interval: 0.4 },
      { time: 6, type: "fighter", count: 6, interval: 0.7 },
      { time: 10, type: "sentinel", count: 3, interval: 0.95 },
      { time: 14, type: "plated", count: 2, interval: 1.2 },
      { time: 18, type: "scout", count: 10, interval: 0.3 },
      { time: 23, type: "hunter", count: 3, interval: 1.05 },
      { time: 30, type: "fighter", count: 8, interval: 0.55 },
      { time: 38, type: "plated", count: 3, interval: 1.1 },
      { time: 44, type: "sentinel", count: 2, interval: 1.0 },
      { time: 48, type: "boss", count: 1 },
    ],
  },

  level2_swarm: {
    id: "level2_swarm",
    baseLevel: "level2",
    variant: "swarm",
    name: "Orion Drift: Swarm",
    background: "purple",
    music: "02_stillness_of_space.ogg",
    difficulty: "Medium",
    description: "Dense skirmisher packs supported by agile sentry drones.",
    enemyScale: { hp: 0.9, damage: 0.96 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 11 }),
      dart: enemy("dart", { hull: 16, speed: 150 }),
      spark: enemy("spark", { hull: 13, shield: 24, speed: 138 }),
      skitter: enemy("skitter", { hull: 20, speed: 118, fireRate: 2.15 }),
      sentinel: enemy("sentinel", { hull: 24, shield: 20, speed: 82, fireRate: 1.85 }),
      boss: boss("level2"),
    },
    events: [
      { time: 1, type: "gnat", count: 14, interval: 0.24 },
      { time: 5, type: "dart", count: 10, interval: 0.38 },
      { time: 9, type: "spark", count: 3, interval: 0.95 },
      { time: 13, type: "gnat", count: 18, interval: 0.2 },
      { time: 18, type: "skitter", count: 4, interval: 0.85 },
      { time: 24, type: "dart", count: 12, interval: 0.32 },
      { time: 30, type: "sentinel", count: 3, interval: 0.95 },
      { time: 36, type: "gnat", count: 20, interval: 0.18 },
      { time: 48, type: "boss", count: 1 },
    ],
  },

  level2_armored: {
    id: "level2_armored",
    baseLevel: "level2",
    variant: "armored",
    name: "Orion Drift: Armored",
    background: "purple",
    music: "02_stillness_of_space.ogg",
    difficulty: "Medium+",
    description: "Plated convoy with flank gunships and one armored command rig.",
    enemyScale: { hp: 1.16, damage: 1.06 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 24, armor: 62, armorClass: 9 }),
      escort: enemy("escort", { hull: 30, armor: 82, armorClass: 9, speed: 56 }),
      duelist: enemy("duelist", { hull: 30, armor: 66, armorClass: 7, speed: 88 }),
      tank: enemy("tank", { hull: 36, armor: 110, armorClass: 10 }),
      boss: boss("level2"),
    },
    events: [
      { time: 2, type: "plated", count: 4, interval: 1.0 },
      { time: 8, type: "escort", count: 3, interval: 1.1 },
      { time: 14, type: "duelist", count: 2, interval: 1.1 },
      { time: 20, type: "plated", count: 5, interval: 0.95 },
      { time: 27, type: "tank", count: 1 },
      { time: 32, type: "escort", count: 4, interval: 0.95 },
      { time: 40, type: "duelist", count: 3, interval: 1.0 },
      { time: 48, type: "boss", count: 1 },
    ],
  },

  level3: {
    id: "level3",
    name: "Nebula Run",
    background: "darkPurple",
    music: "03_racing_through_asteroids_loop.ogg",
    difficulty: "Hard",
    description: "Shield-kites and evasive skitters join the fight. Sustained pressure now matters.",
    completeOnBoss: true,
    enemyTypes: {
      scout: enemy("scout", { hull: 24, speed: 104, score: 128, baseCredit: 18 }),
      fighter: enemy("fighter", { hull: 38, speed: 94, score: 188, baseCredit: 26 }),
      shieldkite: enemy("shieldkite", { hull: 20, shield: 68, shieldRegen: 13, fireRate: 2.25 }),
      skitter: enemy("skitter", { hull: 24, speed: 122, fireRate: 1.95 }),
      plated: enemy("plated", { hull: 26, armor: 74, armorClass: 9, speed: 44 }),
      boss: boss("level3"),
    },
    events: [
      { time: 1, type: "scout", count: 10, interval: 0.35 },
      { time: 7, type: "fighter", count: 7, interval: 0.62 },
      { time: 11, type: "shieldkite", count: 3, interval: 1.0 },
      { time: 15, type: "skitter", count: 3, interval: 0.95 },
      { time: 19, type: "scout", count: 12, interval: 0.28 },
      { time: 24, type: "plated", count: 2, interval: 1.25 },
      { time: 30, type: "shieldkite", count: 4, interval: 0.95 },
      { time: 36, type: "fighter", count: 9, interval: 0.5 },
      { time: 42, type: "skitter", count: 4, interval: 0.85 },
      { time: 48, type: "plated", count: 3, interval: 1.1 },
      { time: 54, type: "boss", count: 1 },
    ],
  },

  level3_swarm: {
    id: "level3_swarm",
    baseLevel: "level3",
    variant: "swarm",
    name: "Nebula Run: Swarm",
    background: "darkPurple",
    music: "03_racing_through_asteroids_loop.ogg",
    difficulty: "Hard",
    description: "High-velocity wing packs with evasive behavior and light shields.",
    enemyScale: { hp: 0.9, damage: 0.97 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 12, speed: 164 }),
      dart: enemy("dart", { hull: 18, speed: 152 }),
      spark: enemy("spark", { hull: 14, shield: 26, speed: 142, fireRate: 1.5 }),
      skitter: enemy("skitter", { hull: 22, speed: 126 }),
      shieldkite: enemy("shieldkite", { hull: 18, shield: 58, speed: 70, fireRate: 2.2 }),
      boss: boss("level3"),
    },
    events: [
      { time: 1, type: "gnat", count: 16, interval: 0.22 },
      { time: 6, type: "dart", count: 12, interval: 0.34 },
      { time: 10, type: "spark", count: 4, interval: 0.85 },
      { time: 14, type: "gnat", count: 22, interval: 0.18 },
      { time: 20, type: "skitter", count: 5, interval: 0.75 },
      { time: 26, type: "dart", count: 14, interval: 0.3 },
      { time: 32, type: "shieldkite", count: 4, interval: 0.9 },
      { time: 40, type: "spark", count: 5, interval: 0.85 },
      { time: 54, type: "boss", count: 1 },
    ],
  },

  level3_armored: {
    id: "level3_armored",
    baseLevel: "level3",
    variant: "armored",
    name: "Nebula Run: Armored",
    background: "darkPurple",
    music: "03_racing_through_asteroids_loop.ogg",
    difficulty: "Hard+",
    description: "Layered armor screens with disciplined flanking escorts.",
    enemyScale: { hp: 1.18, damage: 1.07 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 28, armor: 82, armorClass: 10 }),
      escort: enemy("escort", { hull: 32, armor: 92, armorClass: 10, speed: 60 }),
      duelist: enemy("duelist", { hull: 32, armor: 74, armorClass: 8, speed: 92 }),
      tank: enemy("tank", { hull: 40, armor: 126, armorClass: 11 }),
      bulwark: enemy("bulwark", { hull: 52, armor: 220, armorClass: 13, speed: 26 }),
      boss: boss("level3"),
    },
    events: [
      { time: 2, type: "plated", count: 4, interval: 1.0 },
      { time: 8, type: "escort", count: 3, interval: 1.05 },
      { time: 14, type: "duelist", count: 3, interval: 1.0 },
      { time: 20, type: "plated", count: 5, interval: 0.9 },
      { time: 28, type: "tank", count: 2, interval: 1.4 },
      { time: 36, type: "escort", count: 4, interval: 0.95 },
      { time: 44, type: "bulwark", count: 1 },
      { time: 54, type: "boss", count: 1 },
    ],
  },

  level4: {
    id: "level4",
    name: "Void Cascade",
    background: "asteroidBelt",
    music: "04_emergency_no_alarm.ogg",
    difficulty: "Extreme",
    description: "Combined-defense taskforce. Duelists flank while escorts pin lanes.",
    completeOnBoss: true,
    enemyTypes: {
      drone: enemy("drone", { hull: 26, shield: 20, shieldRegen: 9, speed: 78 }),
      shieldkite: enemy("shieldkite", { hull: 22, shield: 78, shieldRegen: 14, speed: 66 }),
      duelist: enemy("duelist", { hull: 34, armor: 80, armorClass: 9, speed: 98 }),
      escort: enemy("escort", { hull: 36, armor: 106, armorClass: 10, speed: 62, fireRate: 1.8 }),
      stalker: enemy("stalker", { hull: 36, shield: 24, speed: 114, fireRate: 1.7 }),
      tank: enemy("tank", { hull: 50, armor: 162, armorClass: 12, speed: 30 }),
      boss: boss("level4"),
    },
    events: [
      { time: 1, type: "drone", count: 8, interval: 0.38 },
      { time: 6, type: "shieldkite", count: 4, interval: 0.95 },
      { time: 10, type: "duelist", count: 3, interval: 1.0 },
      { time: 14, type: "escort", count: 3, interval: 1.05 },
      { time: 18, type: "stalker", count: 2, interval: 1.2 },
      { time: 22, type: "drone", count: 10, interval: 0.3 },
      { time: 28, type: "tank", count: 1 },
      { time: 32, type: "duelist", count: 4, interval: 0.95 },
      { time: 36, type: "escort", count: 4, interval: 0.9 },
      { time: 42, type: "stalker", count: 3, interval: 1.0 },
      { time: 48, type: "tank", count: 2, interval: 1.5 },
      { time: 58, type: "boss", count: 1 },
    ],
  },

  level4_swarm: {
    id: "level4_swarm",
    baseLevel: "level4",
    variant: "swarm",
    name: "Void Cascade: Swarm",
    background: "asteroidBelt",
    music: "04_emergency_no_alarm.ogg",
    difficulty: "Extreme",
    description: "Unstable skirmisher waves and ambush stalkers. Little time to breathe.",
    enemyScale: { hp: 0.9, damage: 0.98 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 12, speed: 166, pattern: "laneShift", patternParams: { shiftEvery: 1.0 } }),
      dart: enemy("dart", { hull: 18, speed: 154, pattern: "spiralIn", patternParams: { amplitude: 120, frequency: 4.8, decay: 0.2 } }),
      spark: enemy("spark", { hull: 14, shield: 28, speed: 146 }),
      skitter: enemy("skitter", { hull: 24, speed: 128, fireRate: 1.85 }),
      stalker: enemy("stalker", { hull: 32, shield: 18, speed: 116 }),
      boss: boss("level4"),
    },
    events: [
      { time: 1, type: "gnat", count: 18, interval: 0.2 },
      { time: 6, type: "dart", count: 14, interval: 0.3 },
      { time: 11, type: "spark", count: 4, interval: 0.8 },
      { time: 16, type: "skitter", count: 5, interval: 0.75 },
      { time: 22, type: "gnat", count: 22, interval: 0.18 },
      { time: 28, type: "stalker", count: 4, interval: 0.9 },
      { time: 34, type: "dart", count: 16, interval: 0.26 },
      { time: 42, type: "spark", count: 6, interval: 0.78 },
      { time: 58, type: "boss", count: 1 },
    ],
  },

  level4_armored: {
    id: "level4_armored",
    baseLevel: "level4",
    variant: "armored",
    name: "Void Cascade: Armored",
    background: "asteroidBelt",
    music: "04_emergency_no_alarm.ogg",
    difficulty: "Extreme+",
    description: "Armor wall doctrine: escorts, duelists, and heavy carriers in sequence.",
    enemyScale: { hp: 1.2, damage: 1.08 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 30, armor: 92, armorClass: 10 }),
      escort: enemy("escort", { hull: 36, armor: 112, armorClass: 11, speed: 60 }),
      duelist: enemy("duelist", { hull: 34, armor: 88, armorClass: 9, speed: 92 }),
      tank: enemy("tank", { hull: 52, armor: 182, armorClass: 13 }),
      bulwark: enemy("bulwark", { hull: 60, armor: 300, armorClass: 15 }),
      boss: boss("level4"),
    },
    events: [
      { time: 2, type: "plated", count: 5, interval: 0.95 },
      { time: 9, type: "escort", count: 4, interval: 1.0 },
      { time: 16, type: "duelist", count: 3, interval: 1.0 },
      { time: 23, type: "plated", count: 6, interval: 0.85 },
      { time: 31, type: "tank", count: 2, interval: 1.35 },
      { time: 40, type: "escort", count: 5, interval: 0.9 },
      { time: 48, type: "bulwark", count: 2, interval: 1.4 },
      { time: 58, type: "boss", count: 1 },
    ],
  },

  level5: {
    id: "level5",
    name: "Annihilation Protocol",
    background: "ionStorm",
    music: "05_building_a_colony_loop_1.ogg",
    difficulty: "Nightmare",
    description: "Full enemy doctrine. Stalker ambushes, gunline escorts, and bulwark priorities.",
    completeOnBoss: true,
    enemyTypes: {
      spark: enemy("spark", { hull: 16, shield: 34, speed: 146, fireRate: 1.45 }),
      stalker: enemy("stalker", { hull: 38, shield: 28, speed: 118, fireRate: 1.65 }),
      duelist: enemy("duelist", { hull: 36, armor: 92, armorClass: 9, speed: 98 }),
      escort: enemy("escort", { hull: 38, armor: 122, armorClass: 11, speed: 64, fireRate: 1.7 }),
      tank: enemy("tank", { hull: 56, armor: 220, armorClass: 13, speed: 30 }),
      bulwark: enemy("bulwark", { hull: 70, armor: 340, armorClass: 15, speed: 24 }),
      hunter: enemy("hunter", { hull: 44, armor: 26, armorClass: 5, speed: 126, fireRate: 1.8 }),
      boss: boss("level5", { empImmune: true }),
    },
    events: [
      { time: 1, type: "spark", count: 8, interval: 0.5 },
      { time: 5, type: "stalker", count: 3, interval: 1.0 },
      { time: 10, type: "duelist", count: 4, interval: 0.95 },
      { time: 14, type: "escort", count: 4, interval: 0.9 },
      { time: 18, type: "tank", count: 1 },
      { time: 22, type: "spark", count: 10, interval: 0.36 },
      { time: 26, type: "hunter", count: 4, interval: 0.9 },
      { time: 30, type: "bulwark", count: 1 },
      { time: 34, type: "stalker", count: 4, interval: 0.85 },
      { time: 38, type: "escort", count: 5, interval: 0.85 },
      { time: 44, type: "tank", count: 2, interval: 1.25 },
      { time: 50, type: "duelist", count: 5, interval: 0.82 },
      { time: 56, type: "bulwark", count: 1 },
      { time: 62, type: "boss", count: 1 },
    ],
  },

  level5_swarm: {
    id: "level5_swarm",
    baseLevel: "level5",
    variant: "swarm",
    name: "Annihilation Protocol: Swarm",
    background: "ionStorm",
    music: "05_building_a_colony_loop_1.ogg",
    difficulty: "Nightmare",
    description: "Overwhelming micro-fleet pressure with hunter packs and evasive skitters.",
    enemyScale: { hp: 0.9, damage: 0.99 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 12, speed: 168, pattern: "laneShift", patternParams: { shiftEvery: 0.95 } }),
      dart: enemy("dart", { hull: 18, speed: 156, pattern: "spiralIn", patternParams: { amplitude: 140, frequency: 5.0, decay: 0.19 } }),
      spark: enemy("spark", { hull: 15, shield: 30, speed: 148 }),
      skitter: enemy("skitter", { hull: 24, speed: 130, fireRate: 1.8 }),
      stalker: enemy("stalker", { hull: 34, shield: 22, speed: 120, fireRate: 1.65 }),
      hunter: enemy("hunter", { hull: 40, armor: 20, armorClass: 4, speed: 130, fireRate: 1.85 }),
      boss: boss("level5", { empImmune: true }),
    },
    events: [
      { time: 1, type: "gnat", count: 20, interval: 0.18 },
      { time: 6, type: "dart", count: 14, interval: 0.28 },
      { time: 10, type: "spark", count: 5, interval: 0.75 },
      { time: 15, type: "skitter", count: 6, interval: 0.7 },
      { time: 21, type: "gnat", count: 24, interval: 0.16 },
      { time: 27, type: "hunter", count: 5, interval: 0.78 },
      { time: 34, type: "dart", count: 16, interval: 0.24 },
      { time: 42, type: "stalker", count: 5, interval: 0.82 },
      { time: 50, type: "spark", count: 6, interval: 0.72 },
      { time: 62, type: "boss", count: 1 },
    ],
  },

  level5_armored: {
    id: "level5_armored",
    baseLevel: "level5",
    variant: "armored",
    name: "Annihilation Protocol: Armored",
    background: "ionStorm",
    music: "05_building_a_colony_loop_1.ogg",
    difficulty: "Nightmare+",
    description: "Heavy armor battlegroup with layered escorts and reinforced haulers.",
    enemyScale: { hp: 1.24, damage: 1.1 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 32, armor: 108, armorClass: 11 }),
      escort: enemy("escort", { hull: 40, armor: 136, armorClass: 12, speed: 58 }),
      duelist: enemy("duelist", { hull: 38, armor: 104, armorClass: 10, speed: 90 }),
      tank: enemy("tank", { hull: 60, armor: 250, armorClass: 14 }),
      bulwark: enemy("bulwark", { hull: 78, armor: 420, armorClass: 16 }),
      boss: boss("level5", { empImmune: true }),
    },
    events: [
      { time: 2, type: "plated", count: 6, interval: 0.9 },
      { time: 9, type: "escort", count: 4, interval: 0.95 },
      { time: 16, type: "duelist", count: 4, interval: 0.95 },
      { time: 24, type: "tank", count: 2, interval: 1.25 },
      { time: 32, type: "plated", count: 7, interval: 0.82 },
      { time: 40, type: "escort", count: 5, interval: 0.86 },
      { time: 48, type: "bulwark", count: 2, interval: 1.35 },
      { time: 62, type: "boss", count: 1 },
    ],
  },

  level6: {
    id: "level6",
    name: "Crimson Fleet",
    background: "nb_aurorawave",
    music: "space_adventure_bpm140.ogg",
    difficulty: "Very Hard",
    description: "Tactical mixed fleet using lane shifts and stalls to force movement errors.",
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 14, speed: 170, pattern: "laneShift", patternParams: { shiftEvery: 1.0, shiftSpeed: 6.0 } }),
      dart: enemy("dart", { hull: 20, speed: 158, pattern: "spiralIn", patternParams: { amplitude: 150, frequency: 5.2, decay: 0.18 } }),
      spark: enemy("spark", { hull: 16, shield: 34, speed: 150, pattern: "laneShift", patternParams: { shiftEvery: 1.15, shiftSpeed: 5.2 } }),
      sentinel: enemy("sentinel", { hull: 36, shield: 44, speed: 86, fireRate: 1.42, aiParams: { holdY: 145, slideSpeed: 0.95, keepOut: 150 } }),
      duelist: enemy("duelist", { hull: 40, armor: 106, armorClass: 10, speed: 102, fireRate: 1.52 }),
      stalker: enemy("stalker", { hull: 40, shield: 28, speed: 122, fireRate: 1.62 }),
      escort: enemy("escort", { hull: 42, armor: 142, armorClass: 12, speed: 64, pattern: "stall", patternParams: { stallY: 170, stallDuration: 1.6, strafeAmp: 110, strafeFreq: 1.7 } }),
      tank: enemy("tank", { hull: 64, armor: 290, armorClass: 15, speed: 30 }),
      bulwark: enemy("bulwark", { hull: 86, armor: 460, armorClass: 17, speed: 24 }),
      boss: boss("level6"),
    },
    events: [
      { time: 1, type: "gnat", count: 14, interval: 0.24 },
      { time: 5, type: "spark", count: 6, interval: 0.8 },
      { time: 9, type: "sentinel", count: 4, interval: 0.9 },
      { time: 13, type: "duelist", count: 4, interval: 0.9 },
      { time: 17, type: "stalker", count: 4, interval: 0.95 },
      { time: 21, type: "tank", count: 1 },
      { time: 24, type: "dart", count: 12, interval: 0.28 },
      { time: 28, type: "escort", count: 4, interval: 0.9 },
      { time: 34, type: "bulwark", count: 1 },
      { time: 40, type: "gnat", count: 16, interval: 0.2 },
      { time: 44, type: "duelist", count: 5, interval: 0.82 },
      { time: 48, type: "sentinel", count: 4, interval: 0.9 },
      { time: 52, type: "tank", count: 2, interval: 1.3 },
      { time: 58, type: "escort", count: 5, interval: 0.82 },
      { time: 63, type: "bulwark", count: 1 },
      { time: 70, type: "boss", count: 1 },
    ],
  },

  level6_swarm: {
    id: "level6_swarm",
    baseLevel: "level6",
    variant: "swarm",
    name: "Crimson Fleet: Swarm",
    background: "nb_aurorawave",
    music: "space_adventure_bpm140.ogg",
    difficulty: "Very Hard",
    description: "Relentless fast movers with lane-hop behavior and evasive skirmish AI.",
    enemyScale: { hp: 0.9, damage: 1.0 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 14, speed: 172, pattern: "laneShift", patternParams: { shiftEvery: 0.9, shiftSpeed: 6.2 } }),
      dart: enemy("dart", { hull: 20, speed: 160, pattern: "spiralIn", patternParams: { amplitude: 160, frequency: 5.3, decay: 0.17 } }),
      spark: enemy("spark", { hull: 16, shield: 34, speed: 152, pattern: "laneShift", patternParams: { shiftEvery: 1.0, shiftSpeed: 5.6 } }),
      skitter: enemy("skitter", { hull: 26, speed: 132, fireRate: 1.7 }),
      stalker: enemy("stalker", { hull: 36, shield: 20, speed: 126, fireRate: 1.6 }),
      boss: boss("level6"),
    },
    events: [
      { time: 1, type: "gnat", count: 22, interval: 0.17 },
      { time: 6, type: "dart", count: 16, interval: 0.24 },
      { time: 11, type: "spark", count: 6, interval: 0.68 },
      { time: 16, type: "skitter", count: 7, interval: 0.62 },
      { time: 22, type: "gnat", count: 26, interval: 0.15 },
      { time: 28, type: "stalker", count: 5, interval: 0.76 },
      { time: 36, type: "dart", count: 18, interval: 0.2 },
      { time: 44, type: "spark", count: 7, interval: 0.64 },
      { time: 52, type: "skitter", count: 8, interval: 0.58 },
      { time: 70, type: "boss", count: 1 },
    ],
  },

  level6_armored: {
    id: "level6_armored",
    baseLevel: "level6",
    variant: "armored",
    name: "Crimson Fleet: Armored",
    background: "nb_aurorawave",
    music: "space_adventure_bpm140.ogg",
    difficulty: "Very Hard+",
    description: "Slow pressure from fortified columns. Every kill requires commitment.",
    enemyScale: { hp: 1.26, damage: 1.1 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 36, armor: 132, armorClass: 12, speed: 42 }),
      escort: enemy("escort", { hull: 44, armor: 168, armorClass: 13, speed: 56, pattern: "stall", patternParams: { stallY: 165, stallDuration: 1.8, strafeAmp: 100, strafeFreq: 1.5 } }),
      duelist: enemy("duelist", { hull: 42, armor: 126, armorClass: 11, speed: 88 }),
      tank: enemy("tank", { hull: 68, armor: 320, armorClass: 16, speed: 28 }),
      bulwark: enemy("bulwark", { hull: 92, armor: 520, armorClass: 18, speed: 22 }),
      boss: boss("level6"),
    },
    events: [
      { time: 2, type: "plated", count: 6, interval: 0.85 },
      { time: 10, type: "escort", count: 5, interval: 0.88 },
      { time: 18, type: "duelist", count: 4, interval: 0.9 },
      { time: 26, type: "tank", count: 2, interval: 1.2 },
      { time: 34, type: "plated", count: 8, interval: 0.78 },
      { time: 42, type: "escort", count: 6, interval: 0.82 },
      { time: 50, type: "duelist", count: 5, interval: 0.85 },
      { time: 58, type: "bulwark", count: 2, interval: 1.25 },
      { time: 70, type: "boss", count: 1 },
    ],
  },

  level7: {
    id: "level7",
    name: "The Gauntlet",
    background: "nb_wreckfield",
    music: "space_battle_bpm130.ogg",
    difficulty: "Hell",
    description: "Endurance mission with mixed doctrine overlap and orbital boss pressure.",
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 15, speed: 176, pattern: "laneShift", patternParams: { shiftEvery: 0.9, shiftSpeed: 6.4 } }),
      dart: enemy("dart", { hull: 22, speed: 164, pattern: "spiralIn", patternParams: { amplitude: 170, frequency: 5.5, decay: 0.16 } }),
      spark: enemy("spark", { hull: 18, shield: 38, speed: 154, pattern: "laneShift", patternParams: { shiftEvery: 1.0, shiftSpeed: 5.9 } }),
      skitter: enemy("skitter", { hull: 28, speed: 136, fireRate: 1.6 }),
      sentinel: enemy("sentinel", { hull: 40, shield: 52, speed: 88, fireRate: 1.3, aiParams: { holdY: 140, slideSpeed: 1.0, keepOut: 155 } }),
      stalker: enemy("stalker", { hull: 42, shield: 32, speed: 126, fireRate: 1.5 }),
      duelist: enemy("duelist", { hull: 44, armor: 132, armorClass: 12, speed: 96, fireRate: 1.42 }),
      escort: enemy("escort", { hull: 46, armor: 176, armorClass: 13, speed: 58, pattern: "stall", patternParams: { stallY: 170, stallDuration: 1.85, strafeAmp: 118, strafeFreq: 1.6 } }),
      tank: enemy("tank", { hull: 74, armor: 360, armorClass: 17, speed: 28 }),
      bulwark: enemy("bulwark", { hull: 102, armor: 620, armorClass: 19, speed: 22 }),
      boss: boss("level7"),
    },
    events: [
      { time: 1, type: "gnat", count: 18, interval: 0.22 },
      { time: 6, type: "dart", count: 12, interval: 0.34 },
      { time: 12, type: "spark", count: 6, interval: 0.72 },
      { time: 16, type: "skitter", count: 6, interval: 0.68 },
      { time: 20, type: "sentinel", count: 5, interval: 0.8 },
      { time: 24, type: "stalker", count: 4, interval: 0.85 },
      { time: 28, type: "duelist", count: 5, interval: 0.82 },
      { time: 32, type: "escort", count: 4, interval: 0.85 },
      { time: 36, type: "tank", count: 2, interval: 1.2 },
      { time: 40, type: "bulwark", count: 1 },
      { time: 44, type: "gnat", count: 22, interval: 0.17 },
      { time: 48, type: "skitter", count: 7, interval: 0.62 },
      { time: 52, type: "sentinel", count: 5, interval: 0.76 },
      { time: 56, type: "duelist", count: 6, interval: 0.75 },
      { time: 60, type: "escort", count: 5, interval: 0.8 },
      { time: 64, type: "tank", count: 2, interval: 1.1 },
      { time: 68, type: "bulwark", count: 1 },
      { time: 72, type: "spark", count: 8, interval: 0.62 },
      { time: 76, type: "stalker", count: 5, interval: 0.78 },
      { time: 80, type: "duelist", count: 6, interval: 0.72 },
      { time: 84, type: "escort", count: 6, interval: 0.74 },
      { time: 88, type: "tank", count: 2, interval: 1.05 },
      { time: 94, type: "boss", count: 1 },
    ],
  },

  level7_swarm: {
    id: "level7_swarm",
    baseLevel: "level7",
    variant: "swarm",
    name: "The Gauntlet: Swarm",
    background: "nb_wreckfield",
    music: "space_battle_bpm130.ogg",
    difficulty: "Hell",
    description: "Maximum density skirmisher push. Precision and area control are mandatory.",
    enemyScale: { hp: 0.88, damage: 1.02 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 15, speed: 178, pattern: "laneShift", patternParams: { shiftEvery: 0.82, shiftSpeed: 6.7 } }),
      dart: enemy("dart", { hull: 22, speed: 166, pattern: "spiralIn", patternParams: { amplitude: 180, frequency: 5.6, decay: 0.15 } }),
      spark: enemy("spark", { hull: 18, shield: 36, speed: 156, pattern: "laneShift", patternParams: { shiftEvery: 0.95, shiftSpeed: 6.1 } }),
      skitter: enemy("skitter", { hull: 30, speed: 138, fireRate: 1.5 }),
      stalker: enemy("stalker", { hull: 40, shield: 24, speed: 128, fireRate: 1.45 }),
      boss: boss("level7"),
    },
    events: [
      { time: 1, type: "gnat", count: 26, interval: 0.15 },
      { time: 6, type: "dart", count: 18, interval: 0.21 },
      { time: 12, type: "spark", count: 8, interval: 0.56 },
      { time: 18, type: "skitter", count: 8, interval: 0.55 },
      { time: 24, type: "gnat", count: 30, interval: 0.13 },
      { time: 32, type: "dart", count: 20, interval: 0.18 },
      { time: 40, type: "stalker", count: 6, interval: 0.66 },
      { time: 52, type: "spark", count: 10, interval: 0.5 },
      { time: 64, type: "skitter", count: 10, interval: 0.5 },
      { time: 76, type: "gnat", count: 32, interval: 0.12 },
      { time: 94, type: "boss", count: 1 },
    ],
  },

  level7_armored: {
    id: "level7_armored",
    baseLevel: "level7",
    variant: "armored",
    name: "The Gauntlet: Armored",
    background: "nb_wreckfield",
    music: "space_battle_bpm130.ogg",
    difficulty: "Hell+",
    description: "Fortress spearhead. Heavy AC values test sustained per-shot damage.",
    enemyScale: { hp: 1.28, damage: 1.12 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 40, armor: 160, armorClass: 13, speed: 40 }),
      escort: enemy("escort", { hull: 48, armor: 200, armorClass: 14, speed: 54, pattern: "stall", patternParams: { stallY: 168, stallDuration: 1.9, strafeAmp: 108, strafeFreq: 1.45 } }),
      duelist: enemy("duelist", { hull: 46, armor: 156, armorClass: 13, speed: 84 }),
      tank: enemy("tank", { hull: 80, armor: 420, armorClass: 18, speed: 26 }),
      bulwark: enemy("bulwark", { hull: 110, armor: 760, armorClass: 20, speed: 20 }),
      boss: boss("level7"),
    },
    events: [
      { time: 2, type: "plated", count: 7, interval: 0.8 },
      { time: 12, type: "escort", count: 6, interval: 0.78 },
      { time: 22, type: "duelist", count: 5, interval: 0.82 },
      { time: 32, type: "tank", count: 3, interval: 1.1 },
      { time: 44, type: "plated", count: 8, interval: 0.72 },
      { time: 56, type: "escort", count: 7, interval: 0.72 },
      { time: 68, type: "duelist", count: 6, interval: 0.78 },
      { time: 80, type: "bulwark", count: 2, interval: 1.2 },
      { time: 94, type: "boss", count: 1 },
    ],
  },

  level8: {
    id: "level8",
    name: "Last Light",
    background: "nb_crimsonstorm",
    music: "space_boss_battle_bpm175.ogg",
    difficulty: "Ultimate",
    description: "Final combined-arms assault. Survive layered threats to reach the command core.",
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 16, speed: 182, pattern: "laneShift", patternParams: { shiftEvery: 0.8, shiftSpeed: 6.8 } }),
      dart: enemy("dart", { hull: 24, speed: 170, pattern: "spiralIn", patternParams: { amplitude: 190, frequency: 5.9, decay: 0.14 } }),
      spark: enemy("spark", { hull: 20, shield: 42, speed: 160, pattern: "laneShift", patternParams: { shiftEvery: 0.9, shiftSpeed: 6.2 } }),
      skitter: enemy("skitter", { hull: 32, speed: 142, fireRate: 1.4 }),
      sentinel: enemy("sentinel", { hull: 44, shield: 60, speed: 90, fireRate: 1.2, aiParams: { holdY: 138, slideSpeed: 1.03, keepOut: 165 } }),
      stalker: enemy("stalker", { hull: 46, shield: 34, speed: 130, fireRate: 1.35 }),
      duelist: enemy("duelist", { hull: 50, armor: 176, armorClass: 14, speed: 94, fireRate: 1.3 }),
      escort: enemy("escort", { hull: 52, armor: 220, armorClass: 15, speed: 56, pattern: "stall", patternParams: { stallY: 172, stallDuration: 2.0, strafeAmp: 120, strafeFreq: 1.5 } }),
      tank: enemy("tank", { hull: 86, armor: 500, armorClass: 19, speed: 24 }),
      bulwark: enemy("bulwark", { hull: 122, armor: 900, armorClass: 22, speed: 18 }),
      hunter: enemy("hunter", { hull: 52, armor: 44, armorClass: 6, speed: 142, fireRate: 1.55 }),
      boss: boss("level8"),
    },
    events: [
      { time: 1, type: "gnat", count: 22, interval: 0.16 },
      { time: 6, type: "dart", count: 16, interval: 0.24 },
      { time: 11, type: "spark", count: 8, interval: 0.6 },
      { time: 16, type: "skitter", count: 7, interval: 0.58 },
      { time: 21, type: "sentinel", count: 6, interval: 0.7 },
      { time: 26, type: "stalker", count: 5, interval: 0.72 },
      { time: 31, type: "duelist", count: 6, interval: 0.72 },
      { time: 36, type: "escort", count: 5, interval: 0.76 },
      { time: 41, type: "tank", count: 2, interval: 1.1 },
      { time: 46, type: "bulwark", count: 1 },
      { time: 50, type: "hunter", count: 5, interval: 0.7 },
      { time: 54, type: "gnat", count: 24, interval: 0.14 },
      { time: 58, type: "dart", count: 18, interval: 0.2 },
      { time: 62, type: "spark", count: 9, interval: 0.54 },
      { time: 66, type: "skitter", count: 8, interval: 0.52 },
      { time: 70, type: "sentinel", count: 6, interval: 0.66 },
      { time: 74, type: "duelist", count: 7, interval: 0.66 },
      { time: 78, type: "escort", count: 6, interval: 0.68 },
      { time: 82, type: "tank", count: 3, interval: 1.0 },
      { time: 86, type: "bulwark", count: 2, interval: 1.15 },
      { time: 90, type: "hunter", count: 6, interval: 0.62 },
      { time: 98, type: "boss", count: 1 },
    ],
  },

  level8_swarm: {
    id: "level8_swarm",
    baseLevel: "level8",
    variant: "swarm",
    name: "Last Light: Swarm",
    background: "nb_crimsonstorm",
    music: "space_boss_battle_bpm175.ogg",
    difficulty: "Ultimate",
    description: "All-out skirmisher storm. Peak movement pressure and projectile density.",
    enemyScale: { hp: 0.86, damage: 1.04 },
    completeOnBoss: true,
    enemyTypes: {
      gnat: enemy("gnat", { hull: 16, speed: 184, pattern: "laneShift", patternParams: { shiftEvery: 0.74, shiftSpeed: 7.0 } }),
      dart: enemy("dart", { hull: 24, speed: 174, pattern: "spiralIn", patternParams: { amplitude: 200, frequency: 6.0, decay: 0.13 } }),
      spark: enemy("spark", { hull: 20, shield: 40, speed: 162, pattern: "laneShift", patternParams: { shiftEvery: 0.86, shiftSpeed: 6.4 } }),
      skitter: enemy("skitter", { hull: 34, speed: 144, fireRate: 1.3 }),
      stalker: enemy("stalker", { hull: 44, shield: 26, speed: 134, fireRate: 1.28 }),
      hunter: enemy("hunter", { hull: 48, armor: 28, armorClass: 5, speed: 146, fireRate: 1.45 }),
      boss: boss("level8"),
    },
    events: [
      { time: 1, type: "gnat", count: 30, interval: 0.12 },
      { time: 6, type: "dart", count: 22, interval: 0.16 },
      { time: 12, type: "spark", count: 10, interval: 0.48 },
      { time: 18, type: "skitter", count: 10, interval: 0.46 },
      { time: 24, type: "gnat", count: 34, interval: 0.11 },
      { time: 32, type: "hunter", count: 7, interval: 0.56 },
      { time: 40, type: "dart", count: 24, interval: 0.14 },
      { time: 52, type: "spark", count: 12, interval: 0.42 },
      { time: 64, type: "skitter", count: 12, interval: 0.42 },
      { time: 76, type: "gnat", count: 36, interval: 0.1 },
      { time: 88, type: "stalker", count: 8, interval: 0.54 },
      { time: 98, type: "boss", count: 1 },
    ],
  },

  level8_armored: {
    id: "level8_armored",
    baseLevel: "level8",
    variant: "armored",
    name: "Last Light: Armored",
    background: "nb_crimsonstorm",
    music: "space_boss_battle_bpm175.ogg",
    difficulty: "Ultimate+",
    description: "Siege doctrine final exam. Heavy AC and stacked armor bars across all waves.",
    enemyScale: { hp: 1.3, damage: 1.14 },
    completeOnBoss: true,
    enemyTypes: {
      plated: enemy("plated", { hull: 44, armor: 200, armorClass: 15, speed: 38 }),
      escort: enemy("escort", { hull: 56, armor: 260, armorClass: 16, speed: 52, pattern: "stall", patternParams: { stallY: 170, stallDuration: 2.05, strafeAmp: 110, strafeFreq: 1.35 } }),
      duelist: enemy("duelist", { hull: 54, armor: 210, armorClass: 15, speed: 82 }),
      tank: enemy("tank", { hull: 92, armor: 620, armorClass: 21, speed: 22 }),
      bulwark: enemy("bulwark", { hull: 130, armor: 1100, armorClass: 24, speed: 17 }),
      boss: boss("level8"),
    },
    events: [
      { time: 2, type: "plated", count: 8, interval: 0.72 },
      { time: 12, type: "escort", count: 7, interval: 0.7 },
      { time: 22, type: "duelist", count: 6, interval: 0.72 },
      { time: 32, type: "tank", count: 3, interval: 0.96 },
      { time: 42, type: "plated", count: 9, interval: 0.66 },
      { time: 52, type: "escort", count: 8, interval: 0.66 },
      { time: 62, type: "duelist", count: 7, interval: 0.68 },
      { time: 72, type: "tank", count: 4, interval: 0.9 },
      { time: 82, type: "bulwark", count: 2, interval: 1.05 },
      { time: 98, type: "boss", count: 1 },
    ],
  },
};

Object.entries(levels).forEach(([id, data]) => {
  const filePath = path.join(LEVELS_DIR, `${id}.json`);
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, "utf8");
  console.log(`wrote ${path.relative(path.join(__dirname, ".."), filePath)}`);
});
